### PR TITLE
[#6097] Pm 2022 alt text img

### PR DESCRIPTION
**Pull request by phillimorland**

### CODE REVIEW

**Review by Rineee — COMMENTED** [review]
It looks good from the code, but I cant install, some webpack error?

**Comment by khamui** [comment]
looking good for single image (block).
The `Aligned Image` seems to miss caption and copyright.

**Review by khamui — COMMENTED** [review]
looking good for single image (block).

The `Aligned Image` block seems to miss caption and copyright.
The `Three Images` block shows caption (different style) and does not show copyright.

Note: and as already mentioned in an issue, the Image slider does not work as expected.

**Comment by phillimorland** [comment]
@khamui cheers, missed out 3 image block totally, aligned one I will investigate

**Comment by phillimorland** [comment]
@khamui should be fixed now, also I didn't update carousel as it's not working anyway and don't think we want captions ect. there and alt does work

**Comment by khamui** [comment]
very nice! working fine.

**Pull request merged**
