### PR TITLE
Update readme: removing obsolete Note and update python version

### PR DESCRIPTION
**Pull request by khamui**
Not really sure what to put here, we added the LICENSE file because the repo turned public. Maybe adding a sentance mentioning that?

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
> Not really sure what to put here, we added the LICENSE file because the repo turned public. Maybe adding a sentance mentioning that?

What do you mean? Add a note on the license to the readme? Or a note that we are public? Yes, sure whatever you think makes sense!

**Comment by phillimorland** [comment]
> > Not really sure what to put here, we added the LICENSE file because the repo turned public. Maybe adding a sentance mentioning that?
> 
> What do you mean? Add a note on the license to the readme? Or a note that we are public? Yes, sure whatever you think makes sense!

@khamui is this ready again? it seems to be in same state?!

**Comment by goapunk** [comment]
I'll just merge :) if you want to add more we can do in a follow-up PR

**Comment by khamui** [comment]
thanks! good for now

**Pull request merged**
