### PR TITLE
Jd 2022 09 wagtail 4

### PR DESCRIPTION
**Pull request by goapunk**
upgrade to wagtail 4

backup your db.sqlite3 before testing as it might break the db if you go back to 3.x

testing:
please test the live preview feature in wagtail when editing pages

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
Installing works with my DB and also with a fresh one. Pages look fine, wagtail looks fancy!
But I cannot add blocks (to the academy landing page and also the index page, I guess also not to the others), because it only shows me the first field and there is no way to open it to see the other fields.

**Comment by goapunk** [comment]
this is blocked till the next wagtail release, see https://github.com/wagtail/wagtail/issues/9117

**Comment by goapunk** [comment]
@fuzzylogic2000 @phillimorland wagtail 4.0.1 has been released which fixes the error, so good for another round of reviewing

**Review by phillimorland — APPROVED** [review]
the second level nav is fixed, there's definitely some design decisions that are a but hokey but otherwise seems to work

**Pull request merged**
